### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by Abdessittir** [Abdessittir/food-app#9]
This is [the link](https://github.com/users/Abdessittir/projects/5/views/1)

## We are 2 team members

**Comment by PinkMoon25** [comment]
Hi @Abdessittir @kennankole , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
Kanban board created :heavy_check_mark: 
all tasks assigned :heavy_check_mark: 
task distribution :heavy_check_mark: 
All tasks from the requirements created :x: 

## Required Changes ♻️

- [ ] Hi team, good jib setting up the kanban board, however please notice that we have create tasks for each project requirements and you are missing one requirement for the general shopping list, please create and assign that task also and re submit for review, missing task :point_down: 
![image](https://user-images.githubusercontent.com/97521557/224679933-6cbf3d1b-fc2c-487b-b835-6b5ead374475.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Abdessittir** [comment]
# Task added

**Comment by PinkMoon25** [comment]
Hi @Abdessittir @kennankole , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Kanban board created :heavy_check_mark: 
all tasks assigned :heavy_check_mark: 
task distribution :heavy_check_mark: 
All tasks from the requirements created :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
